import direct.directbase.DirectStart
from panda3d.core import *
window = WindowProperties()
window.setTitle('House')
window.setSize(1200,800)
base.win.requestProperties(window)
base.setBackgroundColor(100/255, 150/255, 180/255)
scene = loader.loadModel('scene')
scene.reparentTo(render)
house = loader.loadModel('house')
house.reparentTo(render)

house.setPos(-650,1100,0)
house.setHpr(45,0,0)
base.cam.setPos(0,-8000,5000)
base.cam.setHpr(0,-30,0)
base.disableMouse()

sun = loader.loadModel('sun')

sun.setScale(200)
sun.setPos(0,-1600,3000)
sun.setColor((255/255,255/255,100/255,1))
directional_light = DirectionalLight('sun')
sun_light = sun.attachNewNode(directional_light)
scene.setLight(sun_light)
house.setLight(sun_light)
sun_light.setHpr(-90,-45,0)
directional_light.setColor((1,1,100/255,1))
sun_node = render.attachNewNode('change')
sun.reparentTo(sun_node)
sun_node.hprInterval(40,(0,0,360)).loop()
#directional_light.show_frustum()
directional_light.setShadowCaster(True)
scene.setShaderAuto()
directional_light.getLens().setFilmSize(50,60)
house.setShaderAuto()

base.run()
